name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        image: 
        - {name: "cortex_m4-nano_newlib-hf"}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./${{ matrix.image.name }} --tag chent11/cross-compiler:${{ matrix.image.name }}
    - name: Publish to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker image push dockcross/chent11/cross-compiler:${{ matrix.image.name }}
